package com.aahara.backend.entity;

public enum NutrientType {
    CALORIES, PROTEIN, CARBOHYDRATE, FAT, SATURATED_FAT, TRANS_FAT, FIBER, SUGAR,
    SODIUM, CHOLESTEROL, CALCIUM, IRON, POTASSIUM, MAGNESIUM, ZINC,
    VITAMIN_A, VITAMIN_B1, VITAMIN_B2, VITAMIN_B3, VITAMIN_B6, VITAMIN_B12,
    FOLATE, VITAMIN_C, VITAMIN_D, VITAMIN_E, VITAMIN_K
}
